# Generated by Django 5.0.6 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="advertise",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="event_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
