# Generated by Django 5.0.6 on 2024-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_advertise_booking_event_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="price",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
