# Generated by Django 5.0.6 on 2024-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_advertisement_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="image_1",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_10",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_2",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_3",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_4",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_5",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_6",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_7",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_8",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
        migrations.AddField(
            model_name="room",
            name="image_9",
            field=models.ImageField(blank=True, upload_to="rooms/"),
        ),
    ]
